package com.booking.bookbed.entities;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card")
public class Card implements java.io.Serializable {

	private Integer id;
	private String image;
	private String name;
	private double value;
	private boolean status;
	private Set<InvoiceCard> invoiceCards = new HashSet<InvoiceCard>(0);

	public Card() {
	}

	public Card(double value, boolean status) {
		this.value = value;
		this.status = status;
	}

	public Card(String image, String name, double value, boolean status, Set<InvoiceCard> invoiceCards) {
		this.image = image;
		this.name = name;
		this.value = value;
		this.status = status;
		this.invoiceCards = invoiceCards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "image", length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", nullable = false, precision = 22, scale = 0)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<InvoiceCard> getInvoiceCards() {
		return this.invoiceCards;
	}

	public void setInvoiceCards(Set<InvoiceCard> invoiceCards) {
		this.invoiceCards = invoiceCards;
	}

}
