package com.booking.bookbed.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CreditCard generated by hbm2java
 */
@Entity
@Table(name = "credit_card", catalog = "bookinghotel")
public class CreditCard implements java.io.Serializable {

	private int id;
	private Account account;
	private TypeCard typeCard;
	private String nameCard;
	private String cardNumber;
	private String expiresOn;
	private Boolean default_;
	private boolean status;

	public CreditCard() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_account", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type", nullable = false)
	public TypeCard getTypeCard() {
		return this.typeCard;
	}

	public void setTypeCard(TypeCard typeCard) {
		this.typeCard = typeCard;
	}

	@Column(name = "name_card", nullable = false, length = 250)
	public String getNameCard() {
		return this.nameCard;
	}

	public void setNameCard(String nameCard) {
		this.nameCard = nameCard;
	}
	@Column(name = "card_number", nullable = false, length = 20)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}
	@Column(name = "expires_on", nullable = false, length = 250)
	public String getExpiresOn() {
		return this.expiresOn;
	}

	public void setExpiresOn(String expiresOn) {
		this.expiresOn = expiresOn;
	}

	@Column(name = "default_card")
	public Boolean getDefault_() {
		return this.default_;
	}

	public void setDefault_(Boolean default_) {
		this.default_ = default_;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public CreditCard(int id, Account account, TypeCard typeCard, String nameCard, String cardNumber, String expiresOn,
			Boolean default_, boolean status) {
		this.id = id;
		this.account = account;
		this.typeCard = typeCard;
		this.nameCard = nameCard;
		this.cardNumber = cardNumber;
		this.expiresOn = expiresOn;
		this.default_ = default_;
		this.status = status;
	}

	public CreditCard(int id, Account account, TypeCard typeCard, String nameCard, String cardNumber, String expiresOn,
			boolean status) {
		this.id = id;
		this.account = account;
		this.typeCard = typeCard;
		this.nameCard = nameCard;
		this.cardNumber = cardNumber;
		this.expiresOn = expiresOn;
		this.status = status;
	}

}
