package com.booking.bookbed.entities;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partners generated by hbm2java
 */
@Entity
@Table(name = "partners", catalog = "bookinghotel")
public class Partners implements java.io.Serializable {

	private Integer id;
	private TypePart typePart;
	private String name;
	private String image;

	public Partners() {
	}

	public Partners(TypePart typePart, String image) {
		this.typePart = typePart;
		this.image = image;
	}

	public Partners(TypePart typePart, String name, String image) {
		this.typePart = typePart;
		this.name = name;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtype", nullable = false)
	public TypePart getTypePart() {
		return this.typePart;
	}

	public void setTypePart(TypePart typePart) {
		this.typePart = typePart;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image", nullable = false, length = 50)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
