package com.booking.bookbed.entities;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeCard generated by hbm2java
 */
@Entity
@Table(name = "type_card", catalog = "bookinghotel")
public class TypeCard implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private boolean status;
	private Set<CreditCard> creditCards = new HashSet<CreditCard>(0);

	public TypeCard() {
	}

	public TypeCard(int id, String name, boolean status) {
		this.id = id;
		this.name = name;
		this.status = status;
	}

	public TypeCard(int id, String name, String description, boolean status, Set<CreditCard> creditCards) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.status = status;
		this.creditCards = creditCards;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeCard")
	public Set<CreditCard> getCreditCards() {
		return this.creditCards;
	}

	public void setCreditCards(Set<CreditCard> creditCards) {
		this.creditCards = creditCards;
	}

}
